version: '3.11'


services:
  bot:
    build: .
    restart: always
    container_name: exam_qayta-bot
    environment:
      BOT_TOKEN: 6876133315:AAFbdWJf1u9ASPrrdWI76Pcxzu1I85deCYg
      DB_NAME: postgres
      DB_PASSWORD: 1
      DB_HOST: pg
      DB_USER: postgres
      DB_PORT: 5432
    depends_on:
      - pg
    command: python3 javob_3.py


  pg:
    image: postgres
    restart: always
    container_name: exam_qayta
    environment:
      POSTGRES_PASSWORD: 1
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data/

volumes:
  pg_data: